networks:
  app-network:
    driver: bridge
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run frontend
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "4000:4000"
    working_dir: /app
    command: npm run backend
  nginx:
    image: nginx:1.29
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network