version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    working_dir: /app
    command: npm run next
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://backend:4000
    working_dir: /app
    command: npm run dev
